### ISSUE TITLE
Automated Tools Should Consider Sending User Agent

### ISSUE THREAD

**Issue by eOkadas** [dupdob/AocAutomaton#6]
see https://www.reddit.com/r/adventofcode/comments/z9dhtd/please_include_your_contact_info_in_the_useragent/?utm_source=share&utm_medium=web2x&context=3 post by maintainer of AoC --

The site is receiving unthrottled queries by some tools. To identify the incriminated tools the user agent should be sent in request with the format `github.com/topaz/name-of-tool by yourname@example.com.`

**Comment by eOkadas** [comment]
I opened #2 for this issue but it contained a mistake. Sorry about that :)

=> #3 is opened and tested on 2020 puzzles.

**Comment by dupdob** [comment]
implemented by
